### PR TITLE
config: Update kubernetes to include security patch

### PR DESCRIPTION
**Pull request by Xartos**
**What this PR does / why we need it**:

Update kubernetes version to include security patch.
Will require update on already running clusters.

It might be an idea to do a release of this repo before this PR is merged

**Checklist:**

- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
  - [ ] is completely transparent, will not impact the workload in any way.
  - [x] requires running a migration script.
  - [ ] requires draining and/or replacing nodes.
  - [ ] will break the cluster.
        I.e. full cluster migration is required.

### CODE REVIEW

**Review by viktor-f — DISMISSED** [review]
LGTM! And yes a release before this would be good.

**Review by lentzi90 — COMMENTED** [review]
I don't think this will work unless you also update kubespray. You need to pick a version that [it knows about](https://github.com/kubernetes-sigs/kubespray/blob/a923f4e7c0692229c442b07a531bfb5fc41a23f9/roles/download/defaults/main.yml).

**Comment by Xartos** [comment]
> I don't think this will work unless you also update kubespray. You need to pick a version that [it knows about](https://github.com/kubernetes-sigs/kubespray/blob/a923f4e7c0692229c442b07a531bfb5fc41a23f9/roles/download/defaults/main.yml).

Right I forgot about that... Well I guess we'd just have to wait (or fix it ourselves)

**Comment by cristiklein** [comment]
Seems to be the case on `master`: https://github.com/kubernetes-sigs/kubespray/blob/master/roles/download/defaults/main.yml#L213

Would you like to cherry-pick this to `release-2.15`?

**Comment by Xartos** [comment]
> Seems to be the case on `master`: https://github.com/kubernetes-sigs/kubespray/blob/master/roles/download/defaults/main.yml#L213
> 
> Would you like to cherry-pick this to `release-2.15`?

Oh, I was searching in PRs and issues but didn't find anything about this. I guess githubs search isn't always optimal.
Yea, I'll do that

**Comment by lentzi90** [comment]
Actually, if we just update the the latest commit on the `release-2.15` we already get newer versions. See https://github.com/kubernetes-sigs/kubespray/blob/release-2.15/roles/download/defaults/main.yml#L195

**Comment by Xartos** [comment]
> we already get newer versions

Yea, but we want `1.19.10` (the version that fixes the security issue)
Or that was my intention with this PR.

**Comment by Xartos** [comment]
We can now use this in from the branch `release-2.15` https://github.com/kubernetes-sigs/kubespray/pull/7517

**Comment by viktor-f** [comment]
With the upgrade to kubespray 2.16 we are now using k8s 1.20.7, so this is no longer relevant.

**Pull request closed without merging**
