### PR TITLE
all: Remove SSH key usage

### LINKED ISSUE #21: [1] Do not fiddle with the SSH key
To adhere to the Principle of Least Astonishment (POLA), we should simply use the SSH key to which the user points to, instead of copying around.

Acceptance criteria:
* kubespray does not require pointing to an SSH key, rather uses whatever `ssh` uses by default.
* kubespray does not copy the public SSH key into the `.state` folder.

### PR DESCRIPTION
**Pull request by OlleLarsson**
Removes private ssh key copying and usage.

fixes #21

### CODE REVIEW

**Review by cristiklein — APPROVED** [review]
Loving it!

**Comment by cristiklein** [comment]
@OlleLarsson Forgot to add, could you also update the documentation, or should that be a separate issue?

**Comment by OlleLarsson** [comment]
> @OlleLarsson Forgot to add, could you also update the documentation, or should that be a separate issue?

Perhaps create a separate issue for that :)

**Review by lentzi90 — APPROVED** [review]
LGTM! :+1:

**Review by Xartos — COMMENTED** [review]
Great! Just fix the usage string https://github.com/elastisys/compliantkubernetes-kubespray/blob/ol/rm-ssh-key-usage/bin/ck8s-kubespray#L13

**Comment by OlleLarsson** [comment]
> Great! Just fix the usage string https://github.com/elastisys/compliantkubernetes-kubespray/blob/ol/rm-ssh-key-usage/bin/ck8s-kubespray#L13

Nice, I'd just forgotten to commit the file :)

**Comment by Xartos** [comment]
Actually with this change, sops doesn't seems to be used and we should be able to remove that as well :partying_face:

**Comment by OlleLarsson** [comment]
Alright, i've tested the different commands now and the seem to work :tada:

**Comment by cristiklein** [comment]
Why doesn't this work?

```
$ for CLUSTER in ${SERVICE_CLUSTER} ${WORKLOAD_CLUSTERS[@]}; do     ./bin/ck8s-kubespray init $CLUSTER default; done
error when running /home/cklein/compliantkubernetes-kubespray/bin/init.bash: argument mismatch
error when running /home/cklein/compliantkubernetes-kubespray/bin/init.bash: argument mismatch
```

**Comment by Xartos** [comment]
I guess https://github.com/elastisys/compliantkubernetes-kubespray/blob/main/bin/init.bash#L11-L14 was missed in this PR

**Comment by OlleLarsson** [comment]
https://github.com/elastisys/compliantkubernetes-kubespray/pull/57

**Pull request merged**
