### PR TITLE
Updated the README to be clearer of inventory file

### PR DESCRIPTION
**Pull request by Xartos**
Small fix to make the README not make you feel like you shouldn't change anything in the inventory.ini file that's generated and instead maybe use something else.

### CODE REVIEW

**Review by viktor-f — APPROVED** [review]

**Review by lentzi90 — APPROVED** [review]
Great!

**Comment by Xartos** [comment]
> /lgtm

Sadly we don't have any bot that makes that work :/

**Comment by cristiklein** [comment]
> > /lgtm
> 
> Sadly we don't have any bot that makes that work :/

Just wanted to stay forward-compatible. :smile:

**Pull request merged**
