### PR TITLE
Patch 2.20.0 ck8s2 fixes

### PR DESCRIPTION
**Pull request by davidumea**
**What this PR does / why we need it**:

Fixes from patch release

- [X] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
  - [X] is completely transparent, will not impact the workload in any way.
  - [ ] requires running a migration script.
  - [ ] requires draining and/or replacing nodes.
  - [ ] will break the cluster.
        I.e. full cluster migration is required.

### CODE REVIEW

**Review by OlleLarsson — APPROVED** [review]

**Review by Xartos — COMMENTED** [review]
You don't need to merge back patches into main since they are already there. So you can just close this one

**Comment by davidumea** [comment]
> You don't need to merge back patches into main since they are already there. So you can just close this one

These changes are not on main currently

**Review by crssnd — APPROVED** [review]

**Review by Xartos — CHANGES_REQUESTED** [review]
I can see it being there https://github.com/elastisys/compliantkubernetes-kubespray/commit/1a5109a51749a5646eb719def51c64648cde1ec4

**Comment by davidumea** [comment]
> I can see it being there [1a5109a](https://github.com/elastisys/compliantkubernetes-kubespray/commit/1a5109a51749a5646eb719def51c64648cde1ec4)

but that commit isn't part of this PR :confused:

**Comment by Xartos** [comment]
Alright I see now. The only commit that you should have in this PR (according to me) is [this one](https://github.com/elastisys/compliantkubernetes-kubespray/pull/233/commits/74b2fa8720ca68163fdf4f9e3efa0303957ebe49)
Since the changelog reset for the patch shouldn't be merged back

**Comment by davidumea** [comment]
> Alright I see now. The only commit that you should have in this PR (according to me) is [this one](https://github.com/elastisys/compliantkubernetes-kubespray/pull/233/commits/74b2fa8720ca68163fdf4f9e3efa0303957ebe49) Since the changelog reset for the patch shouldn't be merged back

Why shouldn't we have the updated changelog on the main branch? There was no prior step in the [realease process](https://github.com/elastisys/compliantkubernetes-kubespray/blob/main/release/README.md#patch-releases) for patch releases to merge the "reset changelog" commit to main, but I thought that was just a missed step for this branch. We want `main` to have a fully up-to-date `CHANGELOG.md` file right?

**Comment by Xartos** [comment]
> Why shouldn't we have the updated changelog on the main branch? There was no prior step in the [realease process](https://github.com/elastisys/compliantkubernetes-kubespray/blob/main/release/README.md?rgh-link-date=2022-10-27T10%3A51%3A38Z#patch-releases) for patch releases to merge the "reset changelog" commit to main, but I thought that was just a missed step for this branch. We want `main` to have a fully up-to-date `CHANGELOG.md` file right?

We don't have this for [apps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/CHANGELOG.md) (although I see that it has been done for some (?)) 

So the reason is that we want these changes to not be removed from the WIP-CHANGELOG because these features will be part of the next release.

**Comment by davidumea** [comment]
> We don't have this for [apps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/CHANGELOG.md) (although I see that it has been done for some (?))
> 
> So the reason is that we want these changes to not be removed from the WIP-CHANGELOG because these features will be part of the next release.

Ok fair enough, thanks for explaining. I will remove the changelog commit from this PR

**Review by Xartos — APPROVED** [review]

**Pull request merged**
